### ISSUE TITLE
Fails to work with Vue < 2.1.5

### ISSUE THREAD

**Issue by zxc23** [SimulatedGREG/electron-vue#96]
##### Describe the issue / bug.
\#

When using a Vue version in /app lower than 2.1.5, running dev results in:

[Vue warn]: Error when rendering component <landing-page> at D:\David\Documents\my-project2\app\src\components\LandingPageView.vue: 

Uncaught TypeError: _vm._v is not a function

##### How can I reproduce this problem?
\#

Use vue-cli to init a fresh new project, with Vue 2 and all optional packages enabled except for Vue-Resource (didn't try with a different setup). Disable eslint and testing setup. Next, before using npm install, change the package.json in /app to specify "2.1.4" for Vue instead of "^2.0.1". Then `npm install` and `npm run dev`.

##### If visual, provide a screenshot.
\#

http://i.imgur.com/UYk1wbm.png

##### Tell me about your development environment.
  * Node version: 6.9.4 (also used 6.9.1)
  * NPM version: 4.1.1 (also used 3.x)
  * vue-cli version: 2.7.0
  * Operating System: Windows 10 x64

Right now I'm in a bit of a pickle because vue-icons is currently only working with Vue <= 2.1.4 until it's updated and I need a similar version of Vue for Keen-UI (although this will likely be updated within a few days). I had everything working with an older version of Vue (something like 2.0.3) but accidentally updated both package.jsons and when I tried to reverse the process, I came across this problem.

**Comment by SimulatedGREG** [comment]
@zxc23 

Sorry for the late reply, but this sounds like this might be an issue with keen-ui as it could be related to a recent [VueJS release](https://github.com/vuejs/vue/releases/tag/v2.1.7).
> It is recommended to re-compile the dist file using the latest versions of vue-template-compiler and vue-template-es2015-compiler. The new generated code is backwards-compatible, but code generated by older versions of the compilers may not work properly with the latest runtime.

**Comment by zxc23** [comment]
@SimulatedGREG

But I am getting this error with the default electron-vue project without having added any other packages.

**Comment by SimulatedGREG** [comment]
@zxc23 

Okay after experimenting, this is how I got it to work. This essentially reverts developer dependency versions before the breaking changes.

In `app` directory, `npm install --save vue@2.1.4`
In root directory `npm install --save-dev vue-loader@^10.0.0 vue-template-compiler@2.0.0`.

**Comment by zxc23** [comment]
@SimulatedGREG 

That fixed everything, thanks! I thought it had something to do with vue-loader but I lacked fu to get it going myself.
