### ISSUE TITLE
Error in console : Cannot find module 'vue' 

### ISSUE THREAD

**Issue by jrvaja** [SimulatedGREG/electron-vue#196]
## Found an issue or bug? Tell me all about!
Facing Error in console : Cannot find module 'vue'
##### Describe the issue / bug.
\# I am facing issue with console error. Even I could not see the Hello page.

##### How can I reproduce this problem?
\# Followed by initial setup.

##### If visual, provide a screenshot.
\# 
![screenshot from 2017-04-25 15 09 20](https://cloud.githubusercontent.com/assets/1858318/25379042/4f09d168-29c9-11e7-8abb-9b7949281e1b.png)

##### Tell me about your development environment.
  * Node version: v7.8.0
  * NPM version:4.2.0
  * vue-cli version: (if necessary)
  * Operating System: Ubuntu 14.04

**Comment by SimulatedGREG** [comment]
@jrvaja super sorry for the late reply.

I'm having trouble reproducing this. I'm not entirely sure what the problem is here since the `webpack` output shows a successful compilation. It may have to do with adding `app/node_modules` to the globalPaths in `index.ejs`. I did get this working fine on Ubuntu 16.04, but I don't think using 14.04 is the issue.

The new upcoming structure might avoid this issue entirely. You can test with...
```bash
vue init simulatedgreg/electron-vue#dev my-project
```

**Comment by SimulatedGREG** [comment]
Going to close this due to inactivity. Feel free to comment back if needed.
